MODEL:
  TYPE: sparseformer
  NAME: sparseformer_b

DATA:
  BATCH_SIZE: 128
  IMG_SIZE: 224

EMA:
  ENABLE: True
  DECAY: 0.9999

SF:
  CONV_DIM: 96
  NUM_LATENT_TOKENS: 81
  TOKEN_SAMPLING_POINTS: 36
  WIDTH_CONFIGURATIONS: [384, 768]
  BLOCK_SIZES: [1, 10]
  REPEATS: [4, 1]
  DROP_PATH_RATE: 0.4

TRAIN:
  BASE_LR: 5e-4
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  AUTO_RESUME: False
  CLIP_GRAD: 5.0

SAVE_FREQ: 10

